data_dir: data/train

epochs: 50
batch_size: 8
lr: 0.0001
latent_scale: 1.335256
sample_steps: 50

model: CrossDiT
size: L               # S, B, L, XL
use_seq_compression: false
use_global_cond: true
grad_cp: false

cfg_scale: 1.0
warmup_steps: 0
precision: fp32

vae_ckpt: checkpoints/vae/resnet-vae/final.pt
save_dir: checkpoints/dit/CrossDiT-L 
run_name: CrossDiT-L
